DROP DATABASE IF EXISTS MyMDB_USERS;
CREATE DATABASE MyMDB_USERS;
USE MyMDB_USERS;

CREATE TABLE privilege_level (
	plevel INTEGER NOT NULL,
    pname VARCHAR(20) NOT NULL,
    PRIMARY KEY (plevel)
);

CREATE TABLE session_status (
	statuserus_id INTEGER NOT NULL,
	status VARCHAR(20) NOT NULL,
    PRIMARY KEY (status_id)
);

CREATE TABLE user_status (
	status_id INTEGER NOT NULL,
	status VARCHAR(20) NOT NULL,
    PRIMARY KEY (status_id)
);

CREATE TABLE user (
	user_id INTEGER NOT NULL AUTO_INCREMENT,
    email VARCHAR(50) UNIQUE NOT NULL,
    status INTEGER NOT NULL,
    plevel INTEGER NOT NULL,
    salt VARCHAR(8) NOT NULL,
    pword VARCHAR(128) NOT NULL,
    PRIMARY KEY (user_id),
    FOREIGN KEY (plevel) REFERENCES privilege_level (plevel) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (status) REFERENCES user_status (status_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE session (
	session_id VARCHAR(128) NOT NULL,
    email VARCHAR(50) NOT NULL,
    status INTEGER NOT NULL,
    time_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_used TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expr_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (session_id),
    FOREIGN KEY (status) REFERENCES session_status (status_id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (email) REFERENCES user (email) ON UPDATE CASCADE ON DELETE CASCADE
);